# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07fbb4389813cf89b96a0fb6d47045e93e988284e770a54267883bd91f12896dd82e41df60aee231784fe4d46afc780201ecae846c59db9496ec3990b1736957

test:
  secret_key_base: b28976bf08f96bd5876048f4cf3f3a8f0d91c5cccbae83cf276751ee4bb1f1ee66ec960ea828512855ef2310c6ee86c6144d909dc3ac303c497f42e6b50adf73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
